[package]
name = "simple_token_canister_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs" 

[dependencies]
ic-cdk = "0.17.0"
ic-cdk-macros = "0.17.0"
ic-cdk-timers = "0.10"
candid = "0.10"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0"